package error

const (
	RuleAfter           = "AFTER"
	RuleAfterOrEqual    = "AFTER_OR_EQUAL"
	RuleArray           = "ARRAY"
	RuleArrayOf         = "ARRAY_OF"
	RuleBefore          = "BEFORE"
	RuleBeforeOrEqual   = "BEFORE_OR_EQUAL"
	RuleBetween         = "BETWEEN"
	RuleBoolean         = "BOOLEAN"
	RuleCustom          = "CUSTOM"
	RuleDateFormat      = "DATE_FORMAT"
	RuleDoesntEndWith   = "DOESNT_END_WITH"
	RuleDoesntStartWith = "DOESNT_START_WITH"
	RuleDuration        = "DURATION"
	RuleEmail           = "EMAIL"
	RuleEndsWith        = "ENDS_WITH"
	RuleFilled          = "FILLED"
	RuleFloat           = "FLOAT"
	RuleIn              = "IN"
	RuleInt             = "INT"
	RuleIP              = "IP"
	RuleLength          = "LENGTH"
	RuleMap             = "MAP"
	RuleMax             = "MAX"
	RuleMin             = "MIN"
	RuleNotIn           = "NOT_IN"
	RuleNotRegex        = "NOT_REGEX"
	RuleNumeric         = "NUMERIC"
	RuleRegex           = "REGEX"
	RuleRequired        = "REQUIRED"
	RuleSlice           = "SLICE"
	RuleSliceOf         = "SLICE_OF"
	RuleStartsWith      = "STARTS_WITH"
	RuleString          = "STRING"
	RuleStruct          = "STRUCT"
	RuleURL             = "URL"
	RuleUUID            = "UUID"
)

const (
	TypeArray   = "ARRAY"
	TypeInvalid = "INVALID"
	TypeMap     = "MAP"
	TypeNumber  = "NUMBER"
	TypeSlice   = "SLICE"
	TypeString  = "STRING"
)
