package error

const (
	TypeAfter           = "AFTER"
	TypeAfterOrEqual    = "AFTER_OR_EQUAL"
	TypeArray           = "ARRAY"
	TypeArrayOf         = "ARRAY_OF"
	TypeBefore          = "BEFORE"
	TypeBeforeOrEqual   = "BEFORE_OR_EQUAL"
	TypeBetween         = "BETWEEN"
	TypeBoolean         = "BOOLEAN"
	TypeCustom          = "CUSTOM"
	TypeDateFormat      = "DATE_FORMAT"
	TypeDoesntEndWith   = "DOESNT_END_WITH"
	TypeDoesntStartWith = "DOESNT_START_WITH"
	TypeDuration        = "DURATION"
	TypeEmail           = "EMAIL"
	TypeEndsWith        = "ENDS_WITH"
	TypeFilled          = "FILLED"
	TypeIn              = "IN"
	TypeInt             = "INT"
	TypeIp              = "IP"
	TypeLength          = "LENGTH"
	TypeMap             = "MAP"
	TypeMax             = "MAX"
	TypeMin             = "MIN"
	TypeNotIn           = "NOT_IN"
	TypeNotRegex        = "NOT_REGEX"
	TypeNumeric         = "NUMERIC"
	TypeRegex           = "REGEX"
	TypeRequired        = "REQUIRED"
	TypeSlice           = "SLICE"
	TypeSliceOf         = "SLICE_OF"
	TypeStartsWith      = "STARTS_WITH"
	TypeString          = "STRING"
	TypeStruct          = "STRUCT"
	TypeUrl             = "URL"
)

const (
	SubtypeArray  = "ARRAY"
	SubtypeMap    = "MAP"
	SubtypeNumber = "NUMBER"
	SubtypeSlice  = "SLICE"
	SubtypeString = "STRING"
)
